spring.application.name=nexus-gold

spring.datasource.url=jdbc:postgresql://localhost:5432/nexus-gold-db
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update

server.port=8082

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nexusgold316@gmail.com
spring.mail.password=ghiy ylsh dkxd wlrk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.email.verification.expiration-minutes=15
app.password-reset.expiration-minutes=15