spring.application.name=nexus-gold

spring.datasource.url=jdbc:postgresql://localhost:5432/nexus-gold-db
spring.datasource.username=postgres
spring.datasource.password=Scar@01022
spring.jpa.hibernate.ddl-auto=update

server.port=8081